export const volumeLettersCatalog = [
  {
    id: 1,
    slug: 'face-lit',
    title: 'Световое лицо', 
    description: 'Классический выбор. Светится только лицевая часть.',
    price: "от 450 ₸/см",
    images: { day: '/images/letters/face-lit-day.png', night: '/images/letters/face-lit-night.png' },
    badge: "Хит"
  },
  {
    id: 2,
    slug: 'full-lit',
    title: 'Лицо + Борт',
    description: 'Максимальная яркость. Буква светится целиком.',
    price: "от 650 ₸/см",
    images: { day: '/images/letters/full-lit-day.png', night: '/images/letters/full-lit-night.png' },
    badge: "Premium"
  },
  {
    id: 3,
    slug: 'back-lit',
    title: 'Контражур',
    description: 'Эффект парения. Свет падает на фасад.',
    price: "от 550 ₸/см",
    images: { day: '/images/letters/back-lit-day.png', night: '/images/letters/back-lit-night.png' },
    badge: "Стиль"
  },
  {
    id: 4,
    slug: 'combo-lit',
    title: 'Лицо + Контражур',
    description: 'Комбинированная подсветка для вау-эффекта.',
    price: "от 850 ₸/см",
    images: { day: '/images/letters/combo-lit-day.png', night: '/images/letters/combo-lit-night.png' },
  },
  {
    id: 5,
    slug: 'side-lit',
    title: 'Светятся борта',
    description: 'Нестандартно: лицо глухое, светятся грани.',
    price: "от 600 ₸/см",
    images: { day: '/images/letters/side-lit-day.png', night: '/images/letters/side-lit-night.png' },
  },
  {
    id: 6,
    slug: 'perforated',
    title: 'Перфорация',
    description: 'Эффект мерцания и блеска на боковинах.',
    price: "от 750 ₸/см",
    images: { day: '/images/letters/perforated-day.png', night: '/images/letters/perforated-night.png' },
  },
  {
    id: 7,
    slug: 'acrylic-slim',
    title: 'Тонкие (Акрил)',
    description: 'Ультратонкие буквы из массива акрила.',
    price: "от 900 ₸/см",
    images: { day: '/images/letters/acrylic-slim-day.png', night: '/images/letters/acrylic-slim-night.png' },
  },
  {
    id: 8,
    slug: 'loft-lamps',
    title: 'Ретро (Лампы)',
    description: 'Лофт стиль с открытыми лампами.',
    price: "от 1200 ₸/см",
    images: { day: '/images/letters/loft-lamps-day.png', night: '/images/letters/loft-lamps-night.png' },
  },
  {
    id: 9,
    slug: 'pixel-led',
    title: 'Пиксельные',
    description: 'Открытые светодиоды. Сверхъяркость.',
    price: "от 800 ₸/см",
    images: { day: '/images/letters/pixel-led-day.png', night: '/images/letters/pixel-led-night.png' },
  },
  {
    id: 10,
    slug: 'wood-style',
    title: 'Дерево / Эко',
    description: 'Натуральные материалы для уюта.',
    price: "от 350 ₸/см",
    images: { day: '/images/letters/wood-style-day.png', night: '/images/letters/wood-style-night.png' },
  },
  {
    id: 11,
    slug: 'non-lit',
    title: 'Без подсветки',
    description: 'Бюджетное решение. ПВХ или акрил.',
    price: "от 200 ₸/см",
    images: { day: '/images/letters/non-lit-day.png', night: '/images/letters/non-lit-night.png' },
  },
  {
    id: 12,
    slug: 'day-night-effect',
    title: 'День / Ночь',
    description: 'Днем черные, ночью светятся белым.',
    price: "от 700 ₸/см",
    images: { day: '/images/letters/day-night-effect-day.png', night: '/images/letters/day-night-effect-night.png' },
  },
];